In [1]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from concurrent.futures import ThreadPoolExecutor

In [2]:
# NIFTY50
historical_url_1 = 'https://en.wikipedia.org/w/index.php?title=NIFTY_50#Constituents'

tables = pd.read_html(
    historical_url_1,
    match='Symbol', 
    storage_options={'User-Agent': 'Mozilla/5.0'}
)

nifty50_df_1 = tables[0]
ticker_list_1 = nifty50_df_1['Symbol'].astype(str) + '.NS'

In [3]:
def fetch_mcap(ticker):
    """Fetches the market cap for a single ticker."""
    try:
        # .fast_info is a lightweight dictionary that loads instantly
        # compared to the heavy .info dictionary
        stock = yf.Ticker(ticker)
        mcap = stock.fast_info.market_cap
        return ticker, mcap
    except Exception as e:
        # If a ticker is delisted or throws an error, return None safely
        return ticker, None

In [4]:
print(f"Fetching Market Caps for {len(ticker_list_1)} stocks...")

results = []

# ThreadPoolExecutor opens 10 parallel connections to Yahoo Finance
# This turns a 10-minute download into a 30-second download
with ThreadPoolExecutor(max_workers=10) as executor:
    # executor.map runs the fetch_mcap function on every ticker in the list simultaneously
    for result in executor.map(fetch_mcap, ticker_list_1):
        results.append(result)

# Convert the results into a clean Pandas DataFrame
mcap_df = pd.DataFrame(results, columns=["Ticker", "Market_Cap_Raw"])

# Clean the data: Drop any failures and sort from largest to smallest
mcap_df = mcap_df.dropna().sort_values(by="Market_Cap_Raw", ascending=False).reset_index(drop=True)

mcap_df['Market_Cap_Cr'] = (mcap_df['Market_Cap_Raw'] / 10000000).round(2)
mcap_df['Market_Cap_pct'] = 100 * (mcap_df['Market_Cap_Cr'] / mcap_df['Market_Cap_Cr'].sum())
mcap_df = mcap_df.drop(columns=['Market_Cap_Raw'])
mcap_df['Cumulative_Cap_pct'] = mcap_df['Market_Cap_pct'].cumsum()
nifty50_mcap = mcap_df.copy()
print("\n--- Top Constituents by Market Cap ---")
display(nifty50_mcap)

Fetching Market Caps for 50 stocks...

--- Top Constituents by Market Cap ---

           Ticker  Market_Cap_Cr  Market_Cap_pct  Cumulative_Cap_pct
0     RELIANCE.NS     1827154.39        9.422983            9.422983
1     HDFCBANK.NS     1247315.90        6.432646           15.855628
2   BHARTIARTL.NS     1139105.19        5.874582           21.730211
3         SBIN.NS      984629.93        5.077924           26.808135
4    ICICIBANK.NS      946638.84        4.881997           31.690131
5          TCS.NS      913313.85        4.710133           36.400265
6   BAJFINANCE.NS      574732.22        2.964003           39.364268
7           LT.NS      544736.58        2.809310           42.173578
8         INFY.NS      523028.08        2.697355           44.870934
9   HINDUNILVR.NS      506480.97        2.612019           47.482953
10      MARUTI.NS      431014.49        2.222824           49.705776
11    AXISBANK.NS      420073.69        2.166400           51.872176
12       TITAN.NS      399613.89        2.060885           53.933061
13   SUNPHARMA.NS      397065.95        2.047745           55.980806
14     HCLTECH.NS      392644.27        2.024941           58.005747
15         M&M.NS      391330.13        2.018164           60.023911
16         ITC.NS      381209.07        1.965968           61.989879
17   KOTAKBANK.NS      372508.43        1.921097           63.910976
18        NTPC.NS      368618.76        1.901037           65.812013
19        ONGC.NS      360425.00        1.858780           67.670793
20  ULTRACEMCO.NS      340918.11        1.758180           69.428973
21  ADANIPORTS.NS      339903.10        1.752945           71.181918
22         BEL.NS      323421.17        1.667945           72.849862
23    JSWSTEEL.NS      296758.87        1.530442           74.380304
24  BAJAJFINSV.NS      289019.18        1.490527           75.870831
25    ADANIENT.NS      284208.24        1.465716           77.336547
26   POWERGRID.NS      281575.78        1.452140           78.788687
27  BAJAJ-AUTO.NS      274044.47        1.413299           80.201986
28   COALINDIA.NS      267524.04        1.379672           81.581659
29   TATASTEEL.NS      257680.84        1.328909           82.910568
30  SHRIRAMFIN.NS      241750.31        1.246752           84.157320
31   NESTLEIND.NS      240904.32        1.242389           85.399710
32  ASIANPAINT.NS      226295.35        1.167048           86.566758
33    HINDALCO.NS      221821.19        1.143974           87.710732
34     ETERNAL.NS      220864.87        1.139042           88.849774
35       WIPRO.NS      214653.19        1.107007           89.956782
36   EICHERMOT.NS      203650.87        1.050266           91.007048
37     SBILIFE.NS      192914.67        0.994898           92.001946
38      GRASIM.NS      185995.68        0.959215           92.961161
39      INDIGO.NS      176086.78        0.908113           93.869274
40      JIOFIN.NS      154508.40        0.796829           94.666103
41       TRENT.NS      139226.66        0.718018           95.384121
42    HDFCLIFE.NS      130332.06        0.672147           96.056269
43       TECHM.NS      127611.46        0.658117           96.714385
44        TMPV.NS      126158.26        0.650622           97.365007
45  TATACONSUM.NS      108243.35        0.558232           97.923239
46  APOLLOHOSP.NS      108003.85        0.556996           98.480235
47     DRREDDY.NS      102592.33        0.529088           99.009323
48       CIPLA.NS       99316.87        0.512196           99.521519
49   MAXHEALTH.NS       92779.30        0.478481          100.000000

In [5]:
historical_url_2 = 'https://en.wikipedia.org/w/index.php?title=NIFTY_500#Constituents' # 26 Nov 2024

tables = pd.read_html(
    historical_url_2,
    match='Symbol', 
    storage_options={'User-Agent': 'Mozilla/5.0'}
)

nifty500_df = tables[0]
header = nifty500_df.iloc[0]
nifty500_df = nifty500_df[1:]
nifty500_df.columns = header
nifty500_df = nifty500_df.reset_index(drop=True)
ticker_list_2 = nifty500_df['Symbol'].astype(str) + '.NS'

print("Historical Constituents List:")
print(ticker_list_2.tolist())

Historical Constituents List:
['360ONE.NS', '3MINDIA.NS', 'ABB.NS', 'ACC.NS', 'AIAENG.NS', 'APLAPOLLO.NS', 'AUBANK.NS', 'AARTIIND.NS', 'AAVAS.NS', 'ABBOTINDIA.NS', 'ACE.NS', 'ADANIENSOL.NS', 'ADANIENT.NS', 'ADANIGREEN.NS', 'ADANIPORTS.NS', 'ADANIPOWER.NS', 'ATGL.NS', 'AWL.NS', 'ABCAPITAL.NS', 'ABFRL.NS', 'AEGISLOG.NS', 'AETHER.NS', 'AFFLE.NS', 'AJANTPHARM.NS', 'APLLTD.NS', 'ALKEM.NS', 'ALKYLAMINE.NS', 'ALLCARGO.NS', 'ALOKINDS.NS', 'ARE&M.NS', 'AMBER.NS', 'AMBUJACEM.NS', 'ANANDRATHI.NS', 'ANGELONE.NS', 'ANURAS.NS', 'APARINDS.NS', 'APOLLOHOSP.NS', 'APOLLOTYRE.NS', 'APTUS.NS', 'ACI.NS', 'ASAHIINDIA.NS', 'ASHOKLEY.NS', 'ASIANPAINT.NS', 'ASTERDM.NS', 'ASTRAZEN.NS', 'ASTRAL.NS', 'ATUL.NS', 'AUROPHARMA.NS', 'AVANTIFEED.NS', 'DMART.NS', 'AXISBANK.NS', 'BEML.NS', 'BLS.NS', 'BSE.NS', 'BAJAJ-AUTO.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BAJAJHLDNG.NS', 'BALAMINES.NS', 'BALKRISIND.NS', 'BALRAMCHIN.NS', 'BANDHANBNK.NS', 'BANKBARODA.NS', 'BANKINDIA.NS', 'MAHABANK.NS', 'BATAINDIA.NS', 'BAYERCROP.NS', 'BERGEPAINT.NS', 'BDL.NS', 'BEL.NS', 'BHARATFORG.NS', 'BHEL.NS', 'BPCL.NS', 'BHARTIARTL.NS', 'BIKAJI.NS', 'BIOCON.NS', 'BIRLACORPN.NS', 'BSOFT.NS', 'BLUEDART.NS', 'BLUESTARCO.NS', 'BBTC.NS', 'BORORENEW.NS', 'BOSCHLTD.NS', 'BRIGADE.NS', 'BRITANNIA.NS', 'MAPMYINDIA.NS', 'CCL.NS', 'CESC.NS', 'CGPOWER.NS', 'CIEINDIA.NS', 'CRISIL.NS', 'CSBBANK.NS', 'CAMPUS.NS', 'CANFINHOME.NS', 'CANBK.NS', 'CAPLIPOINT.NS', 'CGCL.NS', 'CARBORUNIV.NS', 'CASTROLIND.NS', 'CEATLTD.NS', 'CELLO.NS', 'CENTRALBK.NS', 'CDSL.NS', 'CENTURYPLY.NS', 'ABREL.NS', 'CERA.NS', 'CHALET.NS', 'CHAMBLFERT.NS', 'CHEMPLASTS.NS', 'CHENNPETRO.NS', 'CHOLAHLDNG.NS', 'CHOLAFIN.NS', 'CIPLA.NS', 'CUB.NS', 'CLEAN.NS', 'COALINDIA.NS', 'COCHINSHIP.NS', 'COFORGE.NS', 'COLPAL.NS', 'CAMS.NS', 'CONCORDBIO.NS', 'CONCOR.NS', 'COROMANDEL.NS', 'CRAFTSMAN.NS', 'CREDITACC.NS', 'CROMPTON.NS', 'CUMMINSIND.NS', 'CYIENT.NS', 'DCMSHRIRAM.NS', 'DLF.NS', 'DOMS.NS', 'DABUR.NS', 'DALBHARAT.NS', 'DATAPATTNS.NS', 'DEEPAKFERT.NS', 'DEEPAKNTR.NS', 'DELHIVERY.NS', 'DEVYANI.NS', 'DIVISLAB.NS', 'DIXON.NS', 'LALPATHLAB.NS', 'DRREDDY.NS', 'EIDPARRY.NS', 'EIHOTEL.NS', 'EPL.NS', 'EASEMYTRIP.NS', 'EICHERMOT.NS', 'ELECON.NS', 'ELGIEQUIP.NS', 'EMAMILTD.NS', 'ENDURANCE.NS', 'ENGINERSIN.NS', 'EQUITASBNK.NS', 'ERIS.NS', 'ESCORTS.NS', 'EXIDEIND.NS', 'FDC.NS', 'NYKAA.NS', 'FEDERALBNK.NS', 'FACT.NS', 'FINEORG.NS', 'FINCABLES.NS', 'FINPIPE.NS', 'FSL.NS', 'FIVESTAR.NS', 'FORTIS.NS', 'GAIL.NS', 'GMMPFAUDLR.NS', 'GMRINFRASTRUCT.NS', 'GRSE.NS', 'GICRE.NS', 'GILLETTE.NS', 'GLAND.NS', 'GLAXO.NS', 'ALIVUS.NS', 'GLENMARK.NS', 'MEDANTA.NS', 'GPIL.NS', 'GODFRYPHLP.NS', 'GODREJCP.NS', 'GODREJIND.NS', 'GODREJPROP.NS', 'GRANULES.NS', 'GRAPHITE.NS', 'GRASIM.NS', 'GESHIP.NS', 'GRINDWELL.NS', 'GAEL.NS', 'FLUOROCHEM.NS', 'GUJGASLTD.NS', 'GMDCLTD.NS', 'GNFC.NS', 'GPPL.NS', 'GSFC.NS', 'GSPL.NS', 'HEG.NS', 'HBLENGINE.NS', 'HCLTECH.NS', 'HDFCAMC.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HFCL.NS', 'HAPPSTMNDS.NS', 'HAPPYFORGE.NS', 'HAVELLS.NS', 'HEROMOTOCO.NS', 'HSCL.NS', 'HINDALCO.NS', 'HAL.NS', 'HINDCOPPER.NS', 'HINDPETRO.NS', 'HINDUNILVR.NS', 'HINDZINC.NS', 'POWERINDIA.NS', 'HOMEFIRST.NS', 'HONASA.NS', 'HONAUT.NS', 'HUDCO.NS', 'ICICIBANK.NS', 'ICICIGI.NS', 'ICICIPRULI.NS', 'ISEC.NS', 'IDBI.NS', 'IDFCFIRSTB.NS', 'IFCI.NS', 'IIFL.NS', 'IRB.NS', 'IRCON.NS', 'ITC.NS', 'ITI.NS', 'INDIACEM.NS', 'INDIAMART.NS', 'INDIANB.NS', 'IEX.NS', 'INDHOTEL.NS', 'IOC.NS', 'IOB.NS', 'IRCTC.NS', 'IRFC.NS', 'INDIGOPNTS.NS', 'IGL.NS', 'INDUSTOWER.NS', 'INDUSINDBK.NS', 'NAUKRI.NS', 'INFY.NS', 'INOXWIND.NS', 'INTELLECT.NS', 'INDIGO.NS', 'IPCALAB.NS', 'JBCHEPHARM.NS', 'JKCEMENT.NS', 'JBMA.NS', 'JKLAKSHMI.NS', 'JKPAPER.NS', 'JMFINANCIL.NS', 'JSWENERGY.NS', 'JSWINFRA.NS', 'JSWSTEEL.NS', 'JAIBALAJI.NS', 'J&KBANK.NS', 'JINDALSAW.NS', 'JSL.NS', 'JINDALSTEL.NS', 'JIOFIN.NS', 'JUBLFOOD.NS', 'JUBLINGREA.NS', 'JUBLPHARMA.NS', 'JWL.NS', 'JUSTDIAL.NS', 'JYOTHYLAB.NS', 'KPRMILL.NS', 'KEI.NS', 'KNRCON.NS', 'KPITTECH.NS', 'KRBL.NS', 'KSB.NS', 'KAJARIACER.NS', 'KPIL.NS', 'KALYANKJIL.NS', 'KANSAINER.NS', 'KARURVYSYA.NS', 'KAYNES.NS', 'KEC.NS', 'KFINTECH.NS', 'KOTAKBANK.NS', 'KIMS.NS', 'LTF.NS', 'LTTS.NS', 'LICHSGFIN.NS', 'LTIM.NS', 'LT.NS', 'LATENTVIEW.NS', 'LAURUSLABS.NS', 'LXCHEM.NS', 'LEMONTREE.NS', 'LICI.NS', 'LINDEINDIA.NS', 'LLOYDSME.NS', 'LUPIN.NS', 'MMTC.NS', 'MRF.NS', 'MTARTECH.NS', 'LODHA.NS', 'MGL.NS', 'MAHSEAMLES.NS', 'M&MFIN.NS', 'M&M.NS', 'MHRIL.NS', 'MAHLIFE.NS', 'MANAPPURAM.NS', 'MRPL.NS', 'MANKIND.NS', 'MARICO.NS', 'MARUTI.NS', 'MASTEK.NS', 'MFSL.NS', 'MAXHEALTH.NS', 'MAZDOCK.NS', 'MEDPLUS.NS', 'METROBRAND.NS', 'METROPOLIS.NS', 'MINDACORP.NS', 'MSUMI.NS', 'MOTILALOFS.NS', 'MPHASIS.NS', 'MCX.NS', 'MUTHOOTFIN.NS', 'NATCOPHARM.NS', 'NBCC.NS', 'NCC.NS', 'NHPC.NS', 'NLCINDIA.NS', 'NMDC.NS', 'NSLNISP.NS', 'NTPC.NS', 'NH.NS', 'NATIONALUM.NS', 'NAVINFLUOR.NS', 'NESTLEIND.NS', 'NETWORK18.NS', 'NAM-INDIA.NS', 'NUVAMA.NS', 'NUVOCO.NS', 'OBEROIRLTY.NS', 'ONGC.NS', 'OIL.NS', 'OLECTRA.NS', 'PAYTM.NS', 'OFSS.NS', 'POLICYBZR.NS', 'PCBL.NS', 'PIIND.NS', 'PNBHOUSING.NS', 'PNCINFRA.NS', 'PVRINOX.NS', 'PAGEIND.NS', 'PATANJALI.NS', 'PERSISTENT.NS', 'PETRONET.NS', 'PHOENIXLTD.NS', 'PIDILITIND.NS', 'PEL.NS', 'PPLPHARMA.NS', 'POLYMED.NS', 'POLYCAB.NS', 'POONAWALLA.NS', 'PFC.NS', 'POWERGRID.NS', 'PRAJIND.NS', 'PRESTIGE.NS', 'PRINCEPIPE.NS', 'PRSMJOHNSN.NS', 'PGHH.NS', 'PNB.NS', 'QUESS.NS', 'RRKABEL.NS', 'RBLBANK.NS', 'RECLTD.NS', 'RHIM.NS', 'RITES.NS', 'RADICO.NS', 'RVNL.NS', 'RAILTEL.NS', 'RAINBOW.NS', 'RAJESHEXPO.NS', 'RKFORGE.NS', 'RCF.NS', 'RATNAMANI.NS', 'RTNINDIA.NS', 'RAYMOND.NS', 'REDINGTON.NS', 'RELIANCE.NS', 'RBA.NS', 'ROUTE.NS', 'SBFC.NS', 'SBICARD.NS', 'SBILIFE.NS', 'SJVN.NS', 'SKFINDIA.NS', 'SRF.NS', 'SAFARI.NS', 'SAMMAANCAP.NS', 'MOTHERSON.NS', 'SANOFI.NS', 'SAPPHIRE.NS', 'SAREGAMA.NS', 'SCHAEFFLER.NS', 'SCHNEIDER.NS', 'SHREECEM.NS', 'RENUKA.NS', 'SHRIRAMFIN.NS', 'SHYAMMETL.NS', 'SIEMENS.NS', 'SIGNATURE.NS', 'SOBHA.NS', 'SOLARINDS.NS', 'SONACOMS.NS', 'SONATSOFTW.NS', 'STARHEALTH.NS', 'SBIN.NS', 'SAIL.NS', 'SWSOLAR.NS', 'STLTECH.NS', 'SUMICHEM.NS', 'SPARC.NS', 'SUNPHARMA.NS', 'SUNTV.NS', 'SUNDARMFIN.NS', 'SUNDRMFAST.NS', 'SUNTECK.NS', 'SUPREMEIND.NS', 'SUVENPHAR.NS', 'SUZLON.NS', 'SWANENERGY.NS', 'SYNGENE.NS', 'SYRMA.NS', 'TBOTEK.NS', 'TVSMOTOR.NS', 'TVSSCS.NS', 'TMB.NS', 'TANLA.NS', 'TATACHEM.NS', 'TATACOMM.NS', 'TCS.NS', 'TATACONSUM.NS', 'TATAELXSI.NS', 'TATAINVEST.NS', 'TATAMOTORS.NS', 'TATAPOWER.NS', 'TATASTEEL.NS', 'TATATECH.NS', 'TTML.NS', 'TECHM.NS', 'TEJASNET.NS', 'NIACL.NS', 'RAMCOCEM.NS', 'THERMAX.NS', 'TIMKEN.NS', 'TITAGARH.NS', 'TITAN.NS', 'TORNTPHARM.NS', 'TORNTPOWER.NS', 'TRENT.NS', 'TRIDENT.NS', 'TRIVENI.NS', 'TRITURBINE.NS', 'TIINDIA.NS', 'UCOBANK.NS', 'UNOMINDA.NS', 'UPL.NS', 'UTIAMC.NS', 'UJJIVANSFB.NS', 'ULTRACEMCO.NS', 'UNIONBANK.NS', 'UBL.NS', 'UNITDSPR.NS', 'USHAMART.NS', 'VGUARD.NS', 'VIPIND.NS', 'VAIBHAVGBL.NS', 'VTL.NS', 'VARROC.NS', 'VBL.NS', 'MANYAVAR.NS', 'VEDL.NS', 'VIJAYA.NS', 'IDEA.NS', 'VOLTAS.NS', 'WELCORP.NS', 'WELSPUNLIV.NS', 'WESTLIFE.NS', 'WHIRLPOOL.NS', 'WIPRO.NS', 'YESBANK.NS', 'ZFCVINDIA.NS', 'ZEEL.NS', 'ZENSARTECH.NS', 'ETERNAL.NS', 'ZYDUSLIFE.NS', 'ECLERX.NS']

In [6]:
print(f"Fetching Market Caps for {len(ticker_list_2)} stocks...")

results = []

# ThreadPoolExecutor opens 10 parallel connections to Yahoo Finance
# This turns a 10-minute download into a 30-second download
with ThreadPoolExecutor(max_workers=10) as executor:
    # executor.map runs the fetch_mcap function on every ticker in the list simultaneously
    for result in executor.map(fetch_mcap, ticker_list_2):
        results.append(result)

# Convert the results into a clean Pandas DataFrame
mcap_df = pd.DataFrame(results, columns=["Ticker", "Market_Cap_Raw"])

# Clean the data: Drop any failures and sort from largest to smallest
mcap_df = mcap_df.dropna().sort_values(by="Market_Cap_Raw", ascending=False).reset_index(drop=True)

mcap_df['Market_Cap_Cr'] = (mcap_df['Market_Cap_Raw'] / 10000000).round(2)
mcap_df['Market_Cap_pct'] = 100 * (mcap_df['Market_Cap_Cr'] / mcap_df['Market_Cap_Cr'].sum())
mcap_df = mcap_df.drop(columns=['Market_Cap_Raw'])
mcap_df['Cumulative_Cap_pct'] = mcap_df['Market_Cap_pct'].cumsum()
nifty500_mcap = mcap_df.copy()

print("\n--- Top Constituents by Market Cap ---")
display(mcap_df)

Fetching Market Caps for 500 stocks...

ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GMRINFRASTRUCT.NS"}}}
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ISEC.NS"}}}
ERROR:yfinance:$ISEC.NS: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$ISEC.NS: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$LTIM.NS: possibly delisted; no price data found  (period=5d)
ERROR:yfinance:$PEL.NS: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$PEL.NS: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$SUVENPHAR.NS: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$SUVENPHAR.NS: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$SWANENERGY.NS: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$SWANENERGY.NS: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$TATAMOTORS.NS: possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$TATAMOTORS.NS: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

--- Top Constituents by Market Cap ---

            Ticker  Market_Cap_Cr  Market_Cap_pct  Cumulative_Cap_pct
0      RELIANCE.NS     1827154.39        4.803672            4.803672
1      HDFCBANK.NS     1247315.90        3.279250            8.082921
2    BHARTIARTL.NS     1139105.19        2.994759           11.077680
3          SBIN.NS      984629.93        2.588637           13.666317
4     ICICIBANK.NS      946638.84        2.488756           16.155073
..             ...            ...             ...                 ...
489  EASEMYTRIP.NS        2913.12        0.007659           99.975274
490       QUESS.NS        2885.08        0.007585           99.982859
491  PRINCEPIPE.NS        2651.98        0.006972           99.989831
492     RAYMOND.NS        2570.88        0.006759           99.996590
493    ALLCARGO.NS        1297.08        0.003410          100.000000

[494 rows x 4 columns]

In [7]:
pd.set_option('display.max_rows', None)
mcap_df

            Ticker  Market_Cap_Cr  Market_Cap_pct  Cumulative_Cap_pct
0      RELIANCE.NS     1827154.39        4.803672            4.803672
1      HDFCBANK.NS     1247315.90        3.279250            8.082921
2    BHARTIARTL.NS     1139105.19        2.994759           11.077680
3          SBIN.NS      984629.93        2.588637           13.666317
4     ICICIBANK.NS      946638.84        2.488756           16.155073
5           TCS.NS      913313.85        2.401143           18.556217
6    BAJFINANCE.NS      574732.22        1.510997           20.067214
7            LT.NS      544736.58        1.432137           21.499351
8          INFY.NS      523028.08        1.375064           22.874415
9    HINDUNILVR.NS      506480.97        1.331561           24.205977
10         LICI.NS      504956.18        1.327553           25.533529
11       MARUTI.NS      431014.49        1.133157           26.666686
12     AXISBANK.NS      420073.69        1.104393           27.771079
13        TITAN.NS      399613.89        1.050603           28.821682
14    SUNPHARMA.NS      397065.95        1.043904           29.865586
15      HCLTECH.NS      392644.27        1.032280           30.897866
16          M&M.NS      391330.13        1.028825           31.926690
17          ITC.NS      381209.07        1.002216           32.928906
18    KOTAKBANK.NS      372508.43        0.979342           33.908248
19         NTPC.NS      368618.76        0.969115           34.877363
20         ONGC.NS      360425.00        0.947574           35.824937
21   ULTRACEMCO.NS      340918.11        0.896289           36.721226
22   ADANIPORTS.NS      339903.10        0.893621           37.614846
23   ADANIPOWER.NS      339067.92        0.891425           38.506271
24          BEL.NS      323421.17        0.850289           39.356560
25     JSWSTEEL.NS      296758.87        0.780192           40.136753
26         VEDL.NS      291217.35        0.765624           40.902376
27   BAJAJFINSV.NS      289019.18        0.759844           41.662221
28        DMART.NS      287320.11        0.755378           42.417598
29     ADANIENT.NS      284208.24        0.747196           43.164794
30    POWERGRID.NS      281575.78        0.740275           43.905070
31          HAL.NS      275013.67        0.723023           44.628093
32   BAJAJ-AUTO.NS      274044.47        0.720475           45.348569
33    COALINDIA.NS      267524.04        0.703333           46.051901
34    TATASTEEL.NS      257680.84        0.677455           46.729356
35   SHRIRAMFIN.NS      241750.31        0.635572           47.364928
36    NESTLEIND.NS      240904.32        0.633348           47.998277
37     HINDZINC.NS      238561.50        0.627189           48.625466
38   ASIANPAINT.NS      226295.35        0.594941           49.220407
39     HINDALCO.NS      221821.19        0.583178           49.803584
40      ETERNAL.NS      220864.87        0.580664           50.384248
41        WIPRO.NS      214653.19        0.564333           50.948581
42    EICHERMOT.NS      203650.87        0.535407           51.483988
43          IOC.NS      201877.23        0.530744           52.014733
44      SBILIFE.NS      192914.67        0.507181           52.521914
45       GRASIM.NS      185995.68        0.488991           53.010905
46     TVSMOTOR.NS      182482.12        0.479754           53.490659
47   ADANIGREEN.NS      178776.26        0.470011           53.960670
48       INDIGO.NS      176086.78        0.462940           54.423610
49     DIVISLAB.NS      162373.86        0.426888           54.850498
50       JIOFIN.NS      154508.40        0.406210           55.256708
51          VBL.NS      145971.20        0.383765           55.640473
52          ABB.NS      145366.98        0.382176           56.022649
53    UNIONBANK.NS      144335.58        0.379465           56.402114
54   MUTHOOTFIN.NS      143561.75        0.377430           56.779544
55          PFC.NS      143521.42        0.377324           57.156868
56   BANKBARODA.NS      142827.85        0.375501           57.532369
57   CUMMINSIND.NS      142444.77        0.374494           57.906863
58          DLF.NS      140993.75        0.370679           58.277542
59   TORNTPHARM.NS      140630.86        0.369725           58.647267
60   ADANIENSOL.NS      139258.11        0.366116           59.013383
61        TRENT.NS      139226.66        0.366033           59.379416
62   PIDILITIND.NS      138121.06        0.363127           59.742542
63     CHOLAFIN.NS      134724.11        0.354196           60.096738
64    BRITANNIA.NS      133862.56        0.351931           60.448669
65         LTIM.NS      133507.09        0.350996           60.799665
66          BSE.NS      133259.07        0.350344           61.150009
67         IRFC.NS      131050.23        0.344537           61.494546
68      INDIANB.NS      130352.44        0.342702           61.837249
69     HDFCLIFE.NS      130332.06        0.342649           62.179898
70         BPCL.NS      129873.16        0.341442           62.521340
71    MOTHERSON.NS      128649.52        0.338225           62.859565
72          PNB.NS      128511.90        0.337864           63.197429
73        TECHM.NS      127611.46        0.335496           63.532925
74    TATAPOWER.NS      127605.89        0.335482           63.868407
75    SOLARINDS.NS      127346.65        0.334800           64.203207
76        CANBK.NS      127125.17        0.334218           64.537425
77   POWERINDIA.NS      126790.70        0.333338           64.870763
78   JINDALSTEL.NS      124052.14        0.326139           65.196902
79      SIEMENS.NS      120671.43        0.317251           65.514153
80      POLYCAB.NS      116467.45        0.306198           65.820351
81   INDUSTOWER.NS      115467.76        0.303570           66.123921
82      CGPOWER.NS      115142.49        0.302715           66.426636
83      HDFCAMC.NS      112210.86        0.295007           66.721643
84   BAJAJHLDNG.NS      111265.69        0.292523           67.014166
85     GODREJCP.NS      110316.00        0.290026           67.304191
86     BOSCHLTD.NS      110131.38        0.289540           67.593732
87    AMBUJACEM.NS      110045.58        0.289315           67.883047
88   HEROMOTOCO.NS      109379.08        0.287563           68.170609
89   TATACONSUM.NS      108243.35        0.284577           68.455186
90   APOLLOHOSP.NS      108003.85        0.283947           68.739133
91        LUPIN.NS      106696.46        0.280510           69.019643
92     ASHOKLEY.NS      104566.36        0.274910           69.294552
93      DRREDDY.NS      102592.33        0.269720           69.564272
94         GAIL.NS      101308.83        0.266345           69.830618
95         IDEA.NS      100217.31        0.263476           70.094093
96      MAZDOCK.NS       99642.93        0.261966           70.356059
97        CIPLA.NS       99316.87        0.261109           70.617168
98         BHEL.NS       99137.82        0.260638           70.877806
99       MARICO.NS       98866.27        0.259924           71.137729
100   MAXHEALTH.NS       92779.30        0.243921           71.381650
101    UNITDSPR.NS       92249.02        0.242527           71.624177
102      RECLTD.NS       92123.08        0.242196           71.866373
103   ZYDUSLIFE.NS       92110.66        0.242163           72.108536
104    INDHOTEL.NS       91313.18        0.240066           72.348603
105   ABCAPITAL.NS       89652.25        0.235700           72.584302
106     ICICIGI.NS       89043.32        0.234099           72.818401
107    SHREECEM.NS       87820.54        0.230884           73.049285
108  BHARATFORG.NS       85998.59        0.226094           73.275380
109   JSWENERGY.NS       85848.25        0.225699           73.501079
110     MANKIND.NS       85827.01        0.225643           73.726722
111  PERSISTENT.NS       84861.35        0.223104           73.949826
112    LLOYDSME.NS       84732.22        0.222765           74.172591
113       LODHA.NS       82551.44        0.217031           74.389622
114     HAVELLS.NS       80400.23        0.211376           74.600998
115        IDBI.NS       79586.26        0.209236           74.810234
116  ICICIPRULI.NS       79240.66        0.208327           75.018561
117  AUROPHARMA.NS       78373.37        0.206047           75.224608
118        NHPC.NS       77437.17        0.203586           75.428194
119       DABUR.NS       77279.68        0.203172           75.631366
120   HINDPETRO.NS       76729.28        0.201725           75.833091
121         OIL.NS       76689.12        0.201619           76.034710
122  NATIONALUM.NS       76672.83        0.201576           76.236286
123        NMDC.NS       74791.99        0.196632           76.432918
124       NYKAA.NS       74328.84        0.195414           76.628332
125  TORNTPOWER.NS       74164.53        0.194982           76.823314
126      AUBANK.NS       73358.20        0.192862           77.016176
127         SRF.NS       73317.71        0.192756           77.208931
128       PAYTM.NS       71949.55        0.189159           77.398090
129  FEDERALBNK.NS       71865.36        0.188937           77.587027
130   POLICYBZR.NS       69933.25        0.183858           77.770885
131         LTF.NS       69767.35        0.183422           77.954306
132       GICRE.NS       69754.95        0.183389           78.137695
133        SAIL.NS       68574.98        0.180287           78.317982
134         MCX.NS       67939.99        0.178617           78.496599
135   BANKINDIA.NS       67347.61        0.177060           78.673659
136         IOB.NS       66820.37        0.175674           78.849333
137       ALKEM.NS       65043.36        0.171002           79.020335
138       DIXON.NS       64814.60        0.170401           79.190735
139  INDUSINDBK.NS       64735.93        0.170194           79.360929
140     SBICARD.NS       64470.92        0.169497           79.530426
141         JSL.NS       64329.13        0.169124           79.699550
142      NAUKRI.NS       64160.81        0.168682           79.868232
143      FORTIS.NS       64009.12        0.168283           80.036515
144        ATGL.NS       63938.29        0.168097           80.204611
145  COROMANDEL.NS       63505.91        0.166960           80.371571
146        OFSS.NS       63134.28        0.165983           80.537554
147  PHOENIXLTD.NS       63068.87        0.165811           80.703365
148    UNOMINDA.NS       62335.89        0.163884           80.867249
149      SUZLON.NS       62155.60        0.163410           81.030659
150  LINDEINDIA.NS       61319.36        0.161211           81.191870
151    GLENMARK.NS       61066.67        0.160547           81.352417
152  SCHAEFFLER.NS       61044.40        0.160488           81.512906
153   NAM-INDIA.NS       60956.03        0.160256           81.673162
154  OBEROIRLTY.NS       60792.48        0.159826           81.832988
155     YESBANK.NS       59905.08        0.157493           81.990481
156  LAURUSLABS.NS       59309.44        0.155927           82.146408
157         MRF.NS       57978.55        0.152428           82.298837
158        RVNL.NS       57354.10        0.150787           82.449623
159   APLAPOLLO.NS       57325.36        0.150711           82.600334
160        MFSL.NS       57145.46        0.150238           82.750572
161    PRESTIGE.NS       56959.77        0.149750           82.900322
162  IDFCFIRSTB.NS       56951.85        0.149729           83.050051
163      BIOCON.NS       56449.89        0.148409           83.198460
164        FACT.NS       55492.89        0.145893           83.344354
165    JSWINFRA.NS       55438.46        0.145750           83.490104
166  ABBOTINDIA.NS       54865.35        0.144243           83.634347
167         UPL.NS       54508.15        0.143304           83.777652
168  SUNDARMFIN.NS       54362.58        0.142922           83.920573
169    MAHABANK.NS       54294.68        0.142743           84.063317
170     TIINDIA.NS       53126.39        0.139672           84.202988
171  BERGEPAINT.NS       53064.80        0.139510           84.342498
172      COLPAL.NS       52740.73        0.138658           84.481156
173  GODREJPROP.NS       51702.31        0.135928           84.617083
174  HINDCOPPER.NS       51276.89        0.134809           84.751893
175   PATANJALI.NS       50915.75        0.133860           84.885753
176         BDL.NS       49335.65        0.129706           85.015458
177  SUPREMEIND.NS       48321.58        0.127040           85.142498
178  MOTILALOFS.NS       46913.77        0.123338           85.265836
179  KALYANKJIL.NS       46403.41        0.121997           85.387833
180    APARINDS.NS       45560.54        0.119781           85.507614
181       PIIND.NS       44784.31        0.117740           85.625354
182     MPHASIS.NS       44362.27        0.116630           85.741984
183    JKCEMENT.NS       44193.58        0.116187           85.858171
184  BALKRISIND.NS       43861.74        0.115314           85.973485
185      ASTRAL.NS       43789.98        0.115126           86.088611
186      VOLTAS.NS       43531.20        0.114445           86.203057
187       IRCTC.NS       43384.00        0.114058           86.317115
188    TATACOMM.NS       43006.50        0.113066           86.430181
189         KEI.NS       42628.31        0.112072           86.542253
190      M&MFIN.NS       41976.14        0.110357           86.652610
191      360ONE.NS       41127.61        0.108126           86.760737
192     COFORGE.NS       41113.33        0.108089           86.868825
193     THERMAX.NS       41037.83        0.107890           86.976716
194    PETRONET.NS       40611.00        0.106768           87.083484
195       GLAXO.NS       40555.80        0.106623           87.190107
196     PAGEIND.NS       40239.68        0.105792           87.295899
197  COCHINSHIP.NS       38541.51        0.101327           87.397226
198         UBL.NS       38449.80        0.101086           87.498312
199      RADICO.NS       37418.87        0.098376           87.596688
200     IPCALAB.NS       37078.50        0.097481           87.694169
201    NLCINDIA.NS       37050.93        0.097409           87.791578
202   DALBHARAT.NS       36958.17        0.097165           87.888743
203      CONCOR.NS       36839.46        0.096853           87.985595
204       HUDCO.NS       36826.95        0.096820           88.082415
205  FLUOROCHEM.NS       36762.40        0.096650           88.179065
206        LTTS.NS       36532.26        0.096045           88.275110
207          NH.NS       35641.99        0.093704           88.368814
208     3MINDIA.NS       35456.81        0.093218           88.462032
209     ASTERDM.NS       35253.13        0.092682           88.554714
210      AIAENG.NS       35212.58        0.092575           88.647289
211   DELHIVERY.NS       35211.35        0.092572           88.739862
212     ESCORTS.NS       35152.99        0.092419           88.832280
213  AJANTPHARM.NS       35074.03        0.092211           88.924492
214  BLUESTARCO.NS       34744.85        0.091346           89.015837
215    SONACOMS.NS       34465.86        0.090612           89.106450
216   ENDURANCE.NS       34223.27        0.089975           89.196424
217  TATAINVEST.NS       33678.76        0.088543           89.284967
218     UCOBANK.NS       32938.70        0.086597           89.371565
219  GODFRYPHLP.NS       32781.13        0.086183           89.457748
220  POONAWALLA.NS       32339.71        0.085023           89.542770
221   CENTRALBK.NS       32249.28        0.084785           89.627555
222  JBCHEPHARM.NS       32198.44        0.084651           89.712206
223        PGHH.NS       31772.57        0.083532           89.795738
224  NAVINFLUOR.NS       31725.73        0.083408           89.879146
225        MRPL.NS       30638.10        0.080549           89.959695
226   GODREJIND.NS       30044.68        0.078989           90.038684
227  CHOLAHLDNG.NS       30024.00        0.078934           90.117618
228      CRISIL.NS       29974.62        0.078805           90.196423
229     KPRMILL.NS       29866.25        0.078520           90.274943
230  ANANDRATHI.NS       29708.93        0.078106           90.353049
231    JUBLFOOD.NS       29266.76        0.076944           90.429992
232   LICHSGFIN.NS       29244.10        0.076884           90.506877
233        GRSE.NS       29093.92        0.076489           90.583366
234       GLAND.NS       28698.92        0.075451           90.658817
235     MEDANTA.NS       28647.12        0.075315           90.734131
236        SJVN.NS       28353.47        0.074543           90.808674
237         ITI.NS       28205.01        0.074152           90.882826
238  METROBRAND.NS       27758.05        0.072977           90.955803
239  APOLLOTYRE.NS       27748.99        0.072953           91.028756
240   TATAELXSI.NS       27692.74        0.072805           91.101562
241  STARHEALTH.NS       27625.45        0.072629           91.174190
242    EXIDEIND.NS       27590.12        0.072536           91.246726
243   ZFCVINDIA.NS       27245.04        0.071628           91.318355
244        CDSL.NS       27241.06        0.071618           91.389973
245  KARURVYSYA.NS       27229.66        0.071588           91.461561
246  BANDHANBNK.NS       27075.61        0.071183           91.532744
247         ACC.NS       26752.17        0.070333           91.603076
248        KIMS.NS       26579.23        0.069878           91.672954
249      TIMKEN.NS       26240.81        0.068988           91.741942
250         IRB.NS       26160.95        0.068778           91.810721
251      KAYNES.NS       26138.56        0.068719           91.879440
252       MSUMI.NS       26082.33        0.068572           91.948012
253       NIACL.NS       25661.01        0.067464           92.015476
254    ANGELONE.NS       25594.23        0.067288           92.082764
255       AMBER.NS       25496.36        0.067031           92.149795
256     WELCORP.NS       25363.04        0.066681           92.216476
257      HONAUT.NS       25290.18        0.066489           92.282965
258  MANAPPURAM.NS       25136.63        0.066085           92.349050
259    GILLETTE.NS       25103.65        0.065999           92.415049
260   SCHNEIDER.NS       24151.90        0.063496           92.478545
261        NBCC.NS       24078.60        0.063304           92.541849
262        HSCL.NS       23925.06        0.062900           92.604749
263      NUVAMA.NS       23793.99        0.062555           92.667305
264         AWL.NS       23627.72        0.062118           92.729423
265       SUNTV.NS       23570.20        0.061967           92.791390
266  LALPATHLAB.NS       23454.76        0.061664           92.853054
267    RAMCOCEM.NS       23421.30        0.061576           92.914629
268   SHYAMMETL.NS       23337.80        0.061356           92.975985
269    TATATECH.NS       22988.58        0.060438           93.036423
270         IGL.NS       22607.12        0.059435           93.095859
271  PNBHOUSING.NS       22531.02        0.059235           93.155094
272   GUJGASLTD.NS       22279.75        0.058574           93.213668
273    AEGISLOG.NS       22199.00        0.058362           93.272030
274  ASAHIINDIA.NS       22174.84        0.058299           93.330329
275   BAYERCROP.NS       21608.82        0.056811           93.387140
276    SUMICHEM.NS       20894.24        0.054932           93.442071
277        CESC.NS       20880.39        0.054895           93.496967
278    ASTRAZEN.NS       20747.50        0.054546           93.551513
279   HBLENGINE.NS       20253.25        0.053247           93.604760
280        KPIL.NS       20207.52        0.053126           93.657886
281   DEEPAKNTR.NS       19936.57        0.052414           93.710300
282     RBLBANK.NS       19919.99        0.052371           93.762671
283  AVANTIFEED.NS       19879.60        0.052264           93.814935